name: Test claim REPL

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-claim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone kda-env
        run: |
          git clone https://github.com/CryptoPascal31/kadena_repl_sandbox.git temp-env
          mv temp-env/kda-env ./kda-env

      - name: Setup Pact
        uses: ./.github/actions/setup-pact
        with:
          version: "5.2"

      - name: Run claim.repl
        uses: ./.github/actions/repl
        with:
          target: claim.repl
